<object:meshname="cat";position=(20,10,-10);rotation=(60, 0, 0);scale=(.5f, .5f, .5f);program="light">
<player:meshname="cat";position=(20,10,-10);rotation=(180, 0, 0);scale=(.25f, .25f, .25f);program="light">
<object:meshname="low_poly_tree";position=(-1,1,1);rotation=(0, 0, 0);scale=(3, 3, 3);program="light">
<object:meshname="Tree";position=(10,10,10);rotation=(0, 0, 0);scale=(10, 10, 10);program="light">
<camera:position=(0,0,0);fov=45;up=(0,1,0);>
<object:meshname="cube";position=(-10,10,-10);rotation=(0, 0, 0);scale=(1, 1, 1);program="">
<object:meshname="cube";position=(0,-6,0);rotation=(0, 0, 0);scale=(100, .1f, 100);program="">
<background:face1="background/pos-x.jpg";face2="background/neg-x.jpg";face3="background/pos-y.jpg";face4="background/neg-y.jpg";face5="background/pos-z.jpg";face6="background/neg-z.jpg">
